#' ingest a medicc profiles file
#'
#' This file is part of the standard medicc output files and contains all of
#' the input data and their states, plus the medicc generated state profiles
#' of the internal tree nodes.
#'
#' Applies changes that are needed for other functions.
#'
#' @param meddic_profiles_file file path
#' @return tibble of file contents
#' @export
read_medicc_profiles <- function(meddic_profiles_file) {
  med_profiles <- vroom::vroom(meddic_profiles_file, show_col_types = FALSE) |>
    dplyr::rename(cell_id = sample_id) |>
    dplyr::mutate(
      chr = stringr::str_remove(chrom, "chr")
    )

  return(med_profiles)
}

#' medicc profiles files to foreground assessment
#'
#' This function takes a medicc profile file (see read_medicc_profiles()) and
#' a tree, and marks if changes in states have occurred between parent nodes
#' and tips.
#'
#' @param medicc_profiles imported medicc profiles. See read_medicc_profiles()
#' @param phylogeny phylo object of phylogeny generated by medicc. See
#' read_medicc_tree()
#' @param cn_type string, 'total' or 'allele' to indicate which type of medicc
#' output we are parsing. Characterization of changes is only done for total.
#' @export
medicc_profiles_to_foreground <- function(
    medicc_profiles, phylogeny, cn_type = c("total", "allele")) {
  cn_type <- match.arg(cn_type)

  internal_profiles <- dplyr::filter(
    med_profiles,
    stringr::str_detect(cell_id, "internal")
  )

  tip_profiles <- dplyr::filter(
    med_profiles,
    !stringr::str_detect(cell_id, "internal|diploid")
  )

  if (cn_type == "total") {
    internal_profiles <- dplyr::select(
      internal_profiles,
      parent_node = cell_id,
      parent_state = total_cn,
      chrom, start, end
    )

    tip_profiles <- dplyr::rename(tip_profiles, state = total_cn)
  } else if (cn_type == "allele") {
    internal_profiles <- internal_profiles <- dplyr::select(
      internal_profiles,
      parent_node = cell_id,
      parent_a_state = cn_a,
      parent_b_state = cn_b,
      chrom, start, end
    )
    tip_profiles <- dplyr::rename(tip_profiles, state_a = cn_a, state_b = cn_b)
  }

  tip_profiles <- add_tip_ancestors_to_df(tip_profiles, phylogeny)

  tip_profiles <- dplyr::left_join(
    tip_profiles,
    internal_profiles,
    by = dplyr::join_by(parent_node, chrom, start, end)
  )

  summary_funcs <- list(
    "total" = purrr::partial(
      characterize_foreground_total_state_changes,
      state_col = "state",
      parent_state_col = "parent_state"
    ),
    "allele" = purrr::partial(
      characterize_foreground_allele_state_changes
      # TODO: actually implement this function
    )
  )

  tip_profiles <- summary_funcs[[cn_type]](tip_profiles)

  return(tip_profiles)
}
